"""initial schema

Revision ID: c075463eda2c
Revises: 
Create Date: 2026-06-27 15:04:57.099505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c075463eda2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('github_install_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('account_avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('review_enabled', sa.Boolean(), nullable=False),
    sa.Column('review_categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_github_install_id'), 'installations', ['github_install_id'], unique=True)
    op.create_index(op.f('ix_installations_is_active'), 'installations', ['is_active'], unique=False)
    op.create_table('repositories',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.Text(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repositories_installation_id'), 'repositories', ['installation_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author_login', sa.Text(), nullable=False),
    sa.Column('base_branch', sa.Text(), nullable=False),
    sa.Column('head_branch', sa.Text(), nullable=False),
    sa.Column('head_sha', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('pr_opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pr_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_author_login'), 'pull_requests', ['author_login'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_table('review_runs',
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('bullmq_job_id', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tool_calls_made', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('github_review_id', sa.BigInteger(), nullable=True),
    sa.Column('review_comment_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_idempotency_key'), 'review_runs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_review_runs_pull_request_id'), 'review_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_review_runs_queued_at'), 'review_runs', ['queued_at'], unique=False)
    op.create_index(op.f('ix_review_runs_status'), 'review_runs', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('review_run_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('diff_position', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('was_posted', sa.Boolean(), nullable=False),
    sa.Column('post_failed', sa.Boolean(), nullable=False),
    sa.Column('post_error', sa.Text(), nullable=True),
    sa.Column('developer_reaction', sa.Text(), nullable=True),
    sa.Column('reacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_file_path'), 'findings', ['file_path'], unique=False)
    op.create_index(op.f('ix_findings_review_run_id'), 'findings', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('reasoning_steps',
    sa.Column('review_run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_steps_review_run_id'), 'reasoning_steps', ['review_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reasoning_steps_review_run_id'), table_name='reasoning_steps')
    op.drop_table('reasoning_steps')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_review_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_file_path'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_review_runs_status'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_queued_at'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_pull_request_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_idempotency_key'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_login'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repositories_installation_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_installations_is_active'), table_name='installations')
    op.drop_index(op.f('ix_installations_github_install_id'), table_name='installations')
    op.drop_table('installations')
    # ### end Alembic commands ###
